### PR TITLE
Feature/first milestone

### PR DESCRIPTION
**Pull request by Psiale**
Installed:
Github Actions
Stylelint
Eslint
React-Redux
Redux
Pushed to Heroku

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Well done with the initial setup. You did well with the addition of the necessary packages. There are a few issues I'd like you to work on though:

- [x] Your commit messages should be descriptive, capitalized and written in the imperative tense ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) Check out this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) that guides on how to edit your commit messages.
- [x] Try to customize your `README.md` file such that it is more descriptive of your current project. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Your removal of the unnecessary files left the app broken. Make sure that the `npm start` 
command runs the app as expected.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Rhelli** [comment]
### React-Redux Bookstore - Pull #2
Hi there,

As per the changes requested above, we have made the following changes and fixes to our project:
 - Removed the default react readme file and replaced it with a brief descriptive readme of the project as it stands at the moment. We don't feel that adding any more content to it at this stage is worthwhile as all we have done is run npx create-react-app.
 - Re-added `logo.svg` to the `src` folder which was causing the error upon running `npm start`.
 - Going back to change our previous commit messages which are not capitalised with `git rebase` is **massive overkill**. We will, however, make sure that our commit messages are properly capitalised going forwards.

Let us know if there are any further issues.

All the best,

Alexis and Rory

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi team :hand: 
Nice job working on the requests from the previous review. But we still need to make some changes before moving on.

- [ ] It's really nice that you deleted the README file text that is bootstrapped with `create-react-app`. But your README still lacks descriptive information about the Bookstore project. Although the project it's far to be completed, we can still add relevant information about it in the README file. This requirement is important because it's actually a best practice to fill the README file before even starting to implement the project itself. This will make your repository looks more professional. Please check out this link [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) where you can find a beautiful README template.
Screenshot from 2021-01-21 13-59-59

- [ ] As it said in the requirements, we need to delete unnecessary files or assets. So we need to delete the `logo.svg` file. We can simply fix the error that you had early by deleting **the logo import** and also **all code** that was generated inside the App component. Since that code uses the logo, it makes sense to also add other information there. We can make it return a message:
```JS
function App() {
  return (
    <h1>
      Hello World
    </h1>
  );
}
```

Happy coding :computer: 
**Sergio Torres**

**Comment by Rhelli** [comment]
# React-Redux Bookstore - Pull #3
Hi there,

We have made the following changes to the project as proposed by the TSE above:
 - More detail has been added to the ReadMe, and it is essentially complete for this stage and ready to have the additional information plugged into it as we progress through the future milestones.
 - The boilerplate JS has been removed from `App.js`, along with `logo.svg` and `app.css`. In its place is a simple 'Hello World' message which will act as a placeholder for the code to come, at this moment in time.

Thanks,

Alexis and Rory

**Review by shloch — APPROVED** [review]
## Hello @Psiale 

Great job, we have a much better README
accomplished

Thumbs up, happy coding

**Pull request merged**
